name: Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64 
    - name: Build
      run: dotnet publish -c Release -r linux-x64 --no-restore --self-contained
    - name: Execute unit tests
      run: dotnet test --no-restore -r linux-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MCStatusDSBot.Linux-x64
        path: MCStatusDSBot\bin\Release\net6.0\linux-x64\publish\

